// ESLint Flat Config – v0.4.23
import js from '@eslint/js';

const NODE_GLOBALS = {
  require: 'readable',
  module: 'readable',
  __dirname: 'readable',
  __filename: 'readable',
  exports: 'writable',
  process: 'readable',
  Buffer: 'readable',
  console: 'readable',
  setTimeout: 'readable',
  clearTimeout: 'readable',
  setInterval: 'readable',
  clearInterval: 'readable',
  global: 'readable',
  URL: 'readable',
};

export default [
  js.configs.recommended,
  {
    ignores: [
      'node_modules/',
      'dist/',
      'release/',
      '.cache/',
      '.serena/',
      'Weiterentwicklung/',
      'tv.html',
      'packages/',
      'scripts/',
      'assets/',
    ],
  },
  // ── Preload content (webview browser context) ──
  {
    files: ['preload-content.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        document: 'readable',
        window: 'readable',
        console: 'readable',
        navigator: 'readable',
        HTMLElement: 'readable',
        HTMLVideoElement: 'readable',
        Event: 'readable',
        MutationObserver: 'readable',
        require: 'readable',
        process: 'readable',
        addEventListener: 'readable',
        removeEventListener: 'readable',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      'no-undef': 'error',
      'no-redeclare': 'off',
    },
  },
  // ── Main process (Node.js) ──
  {
    files: ['main.js', 'preload.js', 'updater.js', 'logger.js', 'lib/**/*.js', 'tests/**/*.js', 'scripts/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...NODE_GLOBALS,
        app: 'readable',
        BrowserWindow: 'readable',
        ipcMain: 'readable',
        dialog: 'readable',
        components: 'readable',
        globalShortcut: 'readable',
        session: 'readable',
        nativeTheme: 'readable',
        shell: 'readable',
        Menu: 'readable',
        Notification: 'readable',
        Tray: 'readable',
        global: 'readable',
        window: 'readable',
        fetch: 'readable',
        AbortSignal: 'readable',
        AbortController: 'readable',
        EventSource: 'readable',
        FormData: 'readable',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      'no-undef': 'error',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-useless-catch': 'off',
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-redeclare': 'off',
      'preserve-caught-error': 'off',
    },
  },
  // ── Renderer (Browser only) ──
  {
    files: ['renderer.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        console: 'readable',
        setTimeout: 'readable',
        clearTimeout: 'readable',
        setInterval: 'readable',
        clearInterval: 'readable',
        window: 'readable',
        document: 'readable',
        fetch: 'readable',
        URL: 'readable',
        URLSearchParams: 'readable',
        localStorage: 'readable',
        confirm: 'readable',
        Blob: 'readable',
        FileReader: 'readable',
        Image: 'readable',
        Audio: 'readable',
        navigator: 'readable',
        location: 'readable',
        addEventListener: 'readable',
        removeEventListener: 'readable',
        customElements: 'readable',
        // Global vars from script context
        tvSources: 'writable',
        tvChannels: 'writable',
        tvEpgData: 'writable',
        tvEpgIndex: 'writable',
        Hls: 'readable',
        logger: 'readable',
        // esbuild resolves these at build time
        require: 'readable',
        module: 'readable',
        process: 'readable',
        __dirname: 'readable',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      'no-undef': 'error',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-redeclare': 'off',
    },
  },
];
